# Generated by Django 3.2.8 on 2021-12-01 11:20

import articles.models
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('image', models.ImageField(default='default.png', upload_to=articles.models.upload_to, verbose_name='Image')),
                ('content', tinymce.models.HTMLField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
